<?php
function envmap_menu(){
  $items['envmap'] = array(
    'page callback' => 'envmap_empty',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['envmap/data/%'] = array(
    'title' => 'Data',
    'page callback' => 'envmap_data',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'envmap.data.inc',
    'delivery callback' => 'envmap_delivery_js_callback',
  );
  $items['envmap/autocomplete/%'] = array(
    'title' => 'Data',
    'page callback' => 'envmap_autocomplete',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'envmap.data.inc',
  );
  return $items;
}
function envmap_empty(){
  if(!isset($_GET['qt-front_content'])){
    drupal_set_title('');
  }
  elseif($_GET['qt-front_content'] == 1) {
    drupal_set_title('事業單位查詢');
  }
  elseif($_GET['qt-front_content'] == 0) {
    drupal_set_title('環境地圖');
  }
  return '<div></div>';
}

function envmap_delivery_js_callback($page_result){
  drupal_add_http_header('Content-Type', 'application/javascript; charset=utf-8');
  print $page_result;
}

function envmap_init() {
   $arg = arg();
   $current_path       = current_path();
   $current_path_alias = drupal_lookup_path('alias', $current_path);
   $module_envmap = drupal_get_path('module', 'envmap');
   drupal_add_css('https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css', array('type' => 'external', 'every_page' => TRUE));

   if ($arg[0] == 'envmap') {
     $option = array(
       'preprocess' => FALSE,
       'group' => 101,
     );
     drupal_add_css($module_envmap . '/envmap/vendor/leaflet/leaflet.css');
     drupal_add_css($module_envmap . '/envmap/vendor/markercluster/MarkerCluster.css');
     drupal_add_css($module_envmap . '/envmap/vendor/markercluster/MarkerCluster.Default.css');
     drupal_add_css($module_envmap . '/envmap/vendor/Leaflet.awesome-markers/dist/leaflet.awesome-markers.css');
     drupal_add_css($module_envmap . '/envmap/screen.css');
     drupal_add_css($module_envmap . '/envmap/custom.css');

     drupal_add_js($module_envmap . '/envmap/vendor/jquery.bindings/jquery.bindings.js', $option);
     drupal_add_js($module_envmap . '/envmap/vendor/leaflet/leaflet.js', $option);
     drupal_add_js($module_envmap . '/envmap/vendor/markercluster/leaflet.markercluster-src.js', $option);
     drupal_add_js($module_envmap . '/envmap/vendor/Leaflet.awesome-markers/dist/leaflet.awesome-markers.min.js', $option);
     drupal_add_js($module_envmap . '/envmap/vendor/leaflet.TileLayer.WMTS/leaflet-tilelayer-wmts.js', $option);
     drupal_add_js('https://maps.googleapis.com/maps/api/js?v=3&libraries=places&sensor=false&key='.variable_get('envmap_gmap_api_key', ''), array('type' => 'external'));
     drupal_add_js($module_envmap . '/envmap/map.js', $option);
     drupal_add_js($module_envmap . '/envmap.js', $option);
     drupal_add_js(array('envmap' => $module_envmap), 'setting');
     drupal_add_js($module_envmap . '/js/intro.min.js', $option);
     drupal_add_css($module_envmap . '/css/introjs.min.css', $option);
     drupal_add_css($module_envmap . '/css/introjs-nassim.css', $option);
   }
}

function envmap_cron(){
  module_load_include('inc', 'envmap', 'envmap.data');
  envmap_data_purge();
  envmap_data_realtime();
}

function envmap_flush_caches(){
  module_load_include('inc', 'envmap', 'envmap.data');
  envmap_data_purge($force = TRUE);
}

function envmap_block_info() {
  $blocks = array();

  $blocks['mapform'] = array(
    'info' => t('地圖搜尋'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

function envmap_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'mapform':
      $block['subject'] = t('地圖搜尋');
      $block['content'] = drupal_get_form('envmap_form');
     break;
  }
  return $block;
}

function envmap_form($form_state){
   $form['wrapprefix'] = array(
     '#markup' => '<div id="envmap-form-wrapper">',
   );
 
   $form['factory_address'] = array(
     '#type' => 'textfield',
     //'#title' => '單位地址',
     '#attributes' => array(
       'placeholder' => '地址或縣市（如台中市OO區）',
     ),
   );

   $form['dummy'] = array(
     '#markup' => '<div>或</div>',
   );

   $form['factory_name'] = array(
     '#type' => 'textfield',
     //'#title' => '單位名稱',
     '#attributes' => array(
       'placeholder' => '企業名稱（如中國石油）',
       'data-model' => 'factory.name',
     ),
     '#autocomplete_path' => 'envmap/autocomplete',
   );

   $form['factory'] = array(
     '#type' => 'checkbox',
     '#title' => '污染事業單位分布',
     '#attributes' => array(
       'data-model' => 'factory.enabled',
     ),
   );

   $form['fa'] = array(
     '#type' => 'fieldset',
     '#collapsible' => FALSE,
   );
   $form['fa']['factory_type'] = array(
     '#type' => 'select',
     '#title' => '工廠類型',
     '#options' => array(
     ),
     '#attributes' => array(
       'data-model' => 'factory.type',
     ),
   );

   $form['fa']['factory_poltype'] = array(
     '#type' => 'select',
     '#title' => '排放類型',
     '#options' => array(
     //  'is_air' => t('空氣汙染'),
     //  'is_water' => t('水汙染'),
     ),
     '#attributes' => array(
       'data-model' => 'factory.poltype',
     ),
   );

   $form['fa']['factory_fine'] = array(
     '#type' => 'checkbox',
     '#title' => '有裁罰紀錄',
     '#attributes' => array(
       'data-model' => 'factory.fine',
     ),
   );
   $form['fa']['factory_realtime'] = array(
     '#type' => 'checkbox',
     '#title' => '即時監測數據',
     '#attributes' => array(
       'data-model' => 'factory.realtime',
     ),
   );
   $form['fa']['realtime'] = array(
     '#type' => 'fieldset',
     '#collapsible' => FALSE,
   );
   $form['fa']['realtime']['factory_overhead'] = array(
     '#type' => 'checkbox',
     '#title' => '最近一個月超標？',
     '#attributes' => array(
       'data-model' => 'factory.overhead',
     ),
   );

   $form['airquality'] = array(
     '#type' => 'checkbox',
     '#title' => '空氣品質測站',
     '#attributes' => array(
       'data-model' => 'airquality.enabled',
     ),
   );

   $help = url('node/17');
   $report = url('report/elsewhere');
   $form['helpdesc'] = array(
     '#markup' => '<div class="helpdesc" class="form-note">
       <i class="fa fa-question-circle"></i><span>找不到資料嗎？參考<a class="colorbox-node" href="'.$help.'" target="_blank">資料來源說明</a>，或跟我們<a href="'.$report.'" target="_blank">通報污染</a></span>
     </div>',
   );
   $form['wrapsuffix'] = array(
     '#markup' => '</div><!--end envmap-form-wrapper -->',
   );

   $form['mapgcaa'] = array(
     '#markup' => '<div id="mapgcaa-wrapper" class="mapgcaa-wrapper">
       <div id="sharemap" class="form-note">
       <span class="" id="copy-label" ><i class="fa fa-share-square"></i>分享地圖</span>
       <input type="text" name="copy" id="copy">
       <span class="" id="copy-link"><i class="fa fa-files-o"></i>Ctrl+C 複製</span>
       </div>
     </div><!--end mapgcaa-wrapper-->',
   );

/*
   $form['submit'] = array(
     '#prefix' => '<div class="submit-button">',
     '#type' => 'submit',
     '#value' => '更新地圖',
     '#suffix' => '</div>',
   );
 */

   return $form;
}

function envmap_query_alter(&$query){
  if(isset($query->alterMetaData['view'])) {
    $view =& $query->alterMetaData['view'];
    if($view->name == 'factory_json' && $view->current_display == 'page') {
      // add group by
      $query->groupBy("factory_registration_no");

      // change fields to sum and count
      $fields =& $query->getFields();
      if(!empty($fields['factory_fine_penalty_money'])){
        $f = $fields['factory_fine_penalty_money'];
        $query->addExpression("SUM({$f['table']}.{$f['field']})", $f['alias'].'_');
        $view->field['penalty_money_1']->field_alias = 'factory_fine_penalty_money_';
      }
      if(!empty($fields['factory_fine_id'])){
        $f = $fields['factory_fine_id'];
        $query->addExpression("COUNT({$f['table']}.{$f['field']})", $f['alias']);
      }
      if(!empty($fields['factory_fine_penalty_date'])){
        $f = $fields['factory_fine_penalty_date'];
        $query->addExpression("MAX({$f['table']}.{$f['field']})", $f['alias']);
      }
    }
  }
}
